[build]
  command = "npm run build"
  publish = ".next/server/pages"  # For SSR/SSG
  # OR for static exports:
  # publish = "out"  # If using 'next export'

[build.environment]
  NODE_VERSION = "18"  # Or your preferred Node version (16, 18, 20)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200